name: Builds perfsonar pull collector image

on:
  push:
    branches:
      - "ilija"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ATLASxAOD
          push: true
          build-args: ANALYSISBASE_TAG=21.2.231 
          tags: ivukotic/servicex_func_adl_xaod_transformer:21.2.231
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ATLASxAOD
          push: true
          build-args: ANALYSISBASE_TAG=22.2.107
          tags: ivukotic/servicex_func_adl_xaod_transformer:22.2.107

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: CMS_AOD
          push: true
          tags: ivukotic/servicex_func_adl_cms_aod_transformer:cmssw-5-3-32

  
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: uproot
          push: true
          tags: ivukotic/servicex_func_adl_uproot_transformer:uproot4 